# Generated by Django 5.0.7 on 2024-08-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_response_responsefield'),
        ('survey', '0002_rename_surver_record_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='assessment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.assessment'),
            preserve_default=False,
        ),
    ]
