# Generated by Django 5.0.7 on 2024-08-16 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_response_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsection',
            old_name='form_id',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='inputfield',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='form_id',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='responsefield',
            old_name='inputField_id',
            new_name='inputField',
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
