# Generated by Django 5.0.7 on 2024-08-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_rename_form_id_formsection_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='fields',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResponseField',
        ),
    ]
