# Generated by Django 5.0.7 on 2024-09-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('form', '0008_textfieldresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment'),
        ),
    ]
