
services:
  app:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static-data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - PG_HOST=db
      - PG_NAME=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
  
  db:
    image: postgres:16-alpine
    restart: always
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

  proxy:
    build:
      context: ./proxy
    restart: always
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static
    depends_on:
      - app

volumes:
  postgres-data:
  static-data: