# Generated by Django 5.0.7 on 2024-10-22 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluator_name', models.CharField(max_length=500)),
                ('evaluator_email', models.EmailField(max_length=254)),
                ('evaluator_relationship', models.CharField(max_length=500)),
            ],
        ),
    ]
