# Generated by Django 5.0.7 on 2024-09-03 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0012_alter_assessment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluator_name', models.CharField(max_length=500)),
                ('evaluator_email', models.EmailField(max_length=254)),
                ('evaluator_relationship', models.CharField(max_length=500)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.record')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
