# Generated by Django 5.0.7 on 2024-08-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='surver',
            new_name='survey',
        ),
    ]
