# Generated by Django 5.0.7 on 2024-08-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_record_user_survey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email_temp',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
