# Generated by Django 5.0.7 on 2024-08-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_email_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='email_temp',
            new_name='email_template',
        ),
    ]
