# Generated by Django 5.0.7 on 2024-08-28 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_textfieldresponse'),
        ('survey', '0007_alter_record_user_alter_survey_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.form'),
        ),
    ]
