# Generated by Django 5.0.7 on 2024-08-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_textfieldresponse'),
        ('survey', '0010_alter_survey_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='form',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.form'),
            preserve_default=False,
        ),
    ]
